#!/usr/bin/bash
# declare STRING variable
STRING="Starting node processes"
#print variable on a screen
echo $STRING

CODIUS_PORT=5001 DEBUG=ilp*,codius* node src/index.js&
CODIUS_PORT=5002 DEBUG=ilp*,codius* node src/index.js&

# wait until both background processes finish
wait